stages:
  - test

playwright-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.44.0-jammy

  script:
    - npm ci
    - npx playwright install --with-deps
    - npx playwright test Customer.spec.js --project=chromium

  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 1 week