const {test,expect}=require("@playwright/test")
test.setTimeout(5 * 60 * 1000)

test("practice",async ({ page })=>{
//    await page.goto("https://practicetestautomation.com/practice-test-login/")
// await page.locator('[name="username"]').fill("student")
// await page.locator('[name="password"]').fill("Password123")
// await page.getByRole("button",{name:"Submit"}).click()
// await expect(page).toHaveURL("https://practicetestautomation.com/logged-in-successfully/")
// await page.getByRole("link",{name:"Log out"}).click()
// await expect(page).toHaveURL("https://practicetestautomation.com/practice-test-login/")
await page.goto("https://www.amazon.in/")
await page.waitForTimeout(5000)
await page.getByRole("button",{name:"Delivering to Pallappāl... 641050"}).click()
await page.getByRole("textbox",{name:"or enter an Indian pincode"}).fill("624710")
await page.getByLabel("Apply").click()
await page.waitForTimeout(5000)
await page.locator('[id="twotabsearchtextbox"]').fill("laptop")
await page.locator('[id="nav-search-submit-button"]').click()
await page.waitForTimeout(5000)
})